add example for fixed length namespace
humanitec-architecture/example-library pull request #71
Opened 2024-08-28 09:47 UTC by Nilsty

adding a namespace template example, where the length of the namespace name is predictable.

2024-08-29 15:31 UTC, chrishumanitec requested changes

2024-08-29 15:31 UTC, chrishumanitec commented on resource-definitions/template-driver/namespace/short-namespace.yaml
> +          name: name: {{ substr 0 8 "${context.env.id}" }}-{{ substr 0 8 "${context.app.id}" }}
This looks wrong. There are two `name` properties in line?

Also, would suggest this instead:
```
name: {{ trunc 8 "${context.env.id}" }}-{{ trunc 8  "${context.app.id}" }}
```

2024-08-29 17:34 UTC, astromechza approved these changes

2024-09-09 08:47 UTC, chrishumanitec approved these changes
LGTM

2024-09-09 08:54 UTC, merged